<application>
  <component name="PropertiesComponent">
    <property name="ANDROID_DEBUG_SELECTED_TAB_AndroidRunConfigurationType" value="Variables" />
    <property name="ATTACHED_TOOL_WINDOW.DEFAULT.NELE_EDITOR.COMPONENT_TREE.AUTO_HIDE" value="false" />
    <property name="ATTACHED_TOOL_WINDOW.DEFAULT.NELE_EDITOR.COMPONENT_TREE.LEFT" value="true" />
    <property name="ATTACHED_TOOL_WINDOW.DEFAULT.NELE_EDITOR.COMPONENT_TREE.SPLIT" value="true" />
    <property name="ATTACHED_TOOL_WINDOW.DEFAULT.NELE_EDITOR.PALETTE.AUTO_HIDE" value="false" />
    <property name="ATTACHED_TOOL_WINDOW.DEFAULT.NELE_EDITOR.PALETTE.LEFT" value="true" />
    <property name="ATTACHED_TOOL_WINDOW.DEFAULT.NELE_EDITOR.PALETTE.SPLIT" value="false" />
    <property name="ATTACHED_TOOL_WINDOW.DEFAULT.NELE_EDITOR.PROPERTIES.AUTO_HIDE" value="false" />
    <property name="ATTACHED_TOOL_WINDOW.DEFAULT.NELE_EDITOR.PROPERTIES.LEFT" value="false" />
    <property name="ATTACHED_TOOL_WINDOW.DEFAULT.NELE_EDITOR.PROPERTIES.SPLIT" value="false" />
    <property name="ATTACHED_TOOL_WINDOW.DEFAULT.NELE_EDITOR.TOOL_ORDER" value="PALETTE,PROPERTIES,COMPONENT_TREE" />
    <property name="ATTACHED_TOOL_WINDOW.NELE_EDITOR.COMPONENT_TREE.LEFT" value="true" />
    <property name="ATTACHED_TOOL_WINDOW.NELE_EDITOR.COMPONENT_TREE.SPLIT" value="true" />
    <property name="ATTACHED_TOOL_WINDOW.NELE_EDITOR.LEFT.UNSCALED.WIDTH" value="285" />
    <property name="ATTACHED_TOOL_WINDOW.NELE_EDITOR.PALETTE.LEFT" value="true" />
    <property name="ATTACHED_TOOL_WINDOW.NELE_EDITOR.RIGHT.UNSCALED.WIDTH" value="338" />
    <property name="ATTACHED_TOOL_WINDOW.NELE_EDITOR.TOOL_ORDER" value="PALETTE,PROPERTIES,COMPONENT_TREE" />
    <property name="AndroidEnableDdms" value="true" />
    <property name="AndroidInitConfigurator.V1" value="true" />
    <property name="AndroidInitConfigurator.V2" value="true" />
    <property name="AndroidInitConfigurator.V3" value="true" />
    <property name="AndroidInitConfigurator.V4" value="true" />
    <property name="AndroidInitConfigurator.V5" value="true" />
    <property name="ColorChooser.RecentColors" value="255-42-47-255,,,101-85-255-255,,,255-245-0-255,,,255-0-0-255,,,0-0-121-255,,,0-183-31-255,,,228-25-4-255,,,0-0-0-255,,,10-0-210-255,,,210-40-118-255,,,255-140-0-255,,,113-255-228-255,,,192-127-255-255,,,255-241-180-255,,,89-89-89-255" />
    <property name="CommitChangeListDialog.DETAILS_SPLITTER_PROPORTION_2" value="0.6406504" />
    <property name="CommitChangeListDialog.SPLITTER_PROPORTION_2" value="0.6783217" />
    <property name="Copy.OpenInEditor" value="true" />
    <property name="DefaultHtmlDoctype.MigrateToHtml5" value="true" />
    <property name="DefaultHtmlDoctype.Refreshed" value="2" />
    <property name="DocumentationAutoUpdateEnabled" value="true" />
    <property name="ExpandBeforeRunStepsPanel" value="true" />
    <property name="ExpandRunDashboardTypesPanel" value="false" />
    <property name="GoToClass.includeLibraries" value="false" />
    <property name="GoToClass.toSaveIncludeLibraries" value="false" />
    <property name="GoToFile.includeJavaFiles" value="false" />
    <property name="KEY_GENYMOTION_PATH" value="C:\Program Files\Genymobile\Genymotion" />
    <property name="LOG_FILTER_HISTORY" value="Array" />
    <property name="LOG_FILTER_TAG_HISTORY" value="^(?!eglCodecCommon)" />
    <property name="MemberChooser.copyJavadoc" value="false" />
    <property name="MemberChooser.showClasses" value="true" />
    <property name="MobileminApi" value="24" />
    <property name="MoveClassWithTarget.OpenInEditor" value="false" />
    <property name="MoveFile.OpenInEditor" value="true" />
    <property name="PLUGIN_FILTER" value="geny&#10;bit&#10;bitbucket&#10;git" />
    <property name="SAVED_COMPANY_DOMAIN" value="alexlevankou.by" />
    <property name="SAVED_RENDER_LANGUAGE" value="Java" />
    <property name="SearchEveryWhereHistory" value="ned,&#10;getWeatherSer&#10;getWeatherService" />
    <property name="ShowDocumentationInToolWindow" value="false" />
    <property name="SingleInspectionProfilePanel.HORIZONTAL_DIVIDER_PROPORTION" value="0.5" />
    <property name="SingleInspectionProfilePanel.VERTICAL_DIVIDER_PROPORTION" value="0.5" />
    <property name="Vcs.Push.Splitter.Proportion" value="0.5812641" />
    <property name="android-component-compatibility-check" value="1547332671144" />
    <property name="android.logcat.filter.apply.if.client.selection.changes" value="false" />
    <property name="android.resource_dialog_splitter" value="0.8" />
    <property name="build.toolwindow.Build.selection.state" value="com.intellij.build.BuildTreeConsoleView" />
    <property name="build.toolwindow.Sync.selection.state" value="com.intellij.build.BuildTreeConsoleView" />
    <property name="com.google.gct.enable.cloud.testing" value="true" />
    <property name="com.intellij.diagnostic.IdeErrorsDialogactiveTab" value="1" />
    <property name="com.intellij.openapi.vcs.actions.ShowMessageHistoryAction$1.splitter" value="0.3" />
    <property name="create.member.preselect.anonymous" value="false" />
    <property name="create.project.preferred.importer" value="Gradle" />
    <property name="decompiler.legal.notice.accepted" value="true" />
    <property name="default.storage.format" value=".ide